apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- with .Values.global.annotations }}
  {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- with .Values.fleet.deployment.annotations }}
  {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  labels:
    app: fleet
    release: {{ .Release.Name }}
  {{- with .Values.global.labels }}
  {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- with .Values.fleet.deployment.labels }}
  {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.fleet.deployment.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fleet
      release: {{ .Release.Name }}
      {{- with .Values.fleet.deployment.podLabels }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fleet
        release: {{ .Release.Name }}
        {{- with .Values.fleet.deployment.podLabels }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.fleet.deployment.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fleet
              topologyKey: kubernetes.io/hostname
            weight: 100
      {{- end }}
      containers:
      - args:
        {{- range .Values.fleet.deployment.args }}
        - {{ . }}
        {{- end }}
        command:
        {{- range .Values.fleet.deployment.cmd }}
          - {{ . }}
        {{- end }}
        env:
        - name: FLEET_VULNERABILITIES_DATABASES_PATH
          value: /tmp/vuln
        - name: FLEET_SERVER_ADDRESS
          value: 0.0.0.0:8080
        - name: FLEET_AUTH_BCRYPT_COST
          value: "12"
        - name: FLEET_AUTH_SALT_KEY_SIZE
          value: "24"
        - name: FLEET_APP_TOKEN_KEY_SIZE
          value: "24"
        - name: FLEET_APP_TOKEN_VALIDITY_PERIOD
          value: 120h
        - name: FLEET_SESSION_KEY_SIZE
          value: "64"
        - name: FLEET_SESSION_DURATION
          value: 2160h
        - name: FLEET_LOGGING_DEBUG
          value: {{ .Values.fleet.logging.debug | quote }}
        - name: FLEET_LOGGING_JSON
          value: {{ .Values.fleet.logging.json | quote }}
        - name: FLEET_LOGGING_DISABLE_BANNER
          value: "false"
        - name: FLEET_SERVER_TLS
          value: {{ .Values.fleet.tls | quote }}
        - name: FLEET_MYSQL_ADDRESS
          value: {{ .Release.Name }}-mysql:3306
        - name: FLEET_MYSQL_DATABASE
          value: fleet
        - name: FLEET_MYSQL_USERNAME
          value: fleet
        - name: FLEET_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: fleet-password
        - name: FLEET_MYSQL_MAX_OPEN_CONNS
          value: "50"
        - name: FLEET_MYSQL_MAX_IDLE_CONNS
          value: "50"
        - name: FLEET_MYSQL_CONN_MAX_LIFETIME
          value: "0"
        - name: FLEET_REDIS_ADDRESS
          value: {{ .Release.Name }}-redis-master:6379
        - name: FLEET_REDIS_DATABASE
          value: "0"
        - name: FLEET_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: fleet-password
        - name: FLEET_OSQUERY_NODE_KEY_SIZE
          value: "24"
        - name: FLEET_OSQUERY_LABEL_UPDATE_INTERVAL
          value: 30m
        - name: FLEET_OSQUERY_DETAIL_UPDATE_INTERVAL
          value: 30m
        - name: FLEET_OSQUERY_STATUS_LOG_PLUGIN
          value: filesystem
        - name: FLEET_OSQUERY_RESULT_LOG_PLUGIN
          value: filesystem
        - name: FLEET_FILESYSTEM_STATUS_LOG_FILE
          value: /logs/osquery_status
        - name: FLEET_FILESYSTEM_RESULT_LOG_FILE
          value: /logs/osquery_result
        - name: FLEET_FILESYSTEM_ENABLE_LOG_ROTATION
          value: "false"
        - name: FLEET_FILESYSTEM_ENABLE_LOG_COMPRESSION
          value: "false"
        - name: FLEET_VULNERABILITIES_DISABLE_SCHEDULE
          value: "true"
        - name: FLEET_SERVER_PRIVATE_KEY
        image: {{ .Values.fleet.deployment.image }}
        imagePullPolicy: {{ .Values.fleet.deployment.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: fleet
        ports:
        - containerPort: 8080
          name: fleet
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        {{- if .Values.fleet.deployment.resources }}
        resources:
          {{- with .Values.fleet.deployment.resources }}
          {{- toYaml . | trim | nindent 10 }}
          {{- end }} 
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 3333
          runAsNonRoot: true
          runAsUser: 3333
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /logs
          name: osquery-logs
      restartPolicy: {{ .Values.fleet.deployment.restartPolicy }}
      serviceAccount: fleet
      serviceAccountName: fleet
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir:
          sizeLimit: 20Gi
        name: osquery-logs
