apiVersion: v1
kind: Secret
metadata:
  name: fleet-password
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
type: Opaque
data:
  mysql-password: {{ randAlphaNum 16 | b64enc }}
  mysql-root-password: {{ randAlphaNum 16 | b64enc }}
  mysql-replication-password: {{ randAlphaNum 16 | b64enc }}
  redis-password: {{ randAlphaNum 16 | b64enc }}
