apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.fleet.service.annotations }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  labels:
    app: fleet
    release: {{ .Release.Name }}
    {{- with .Values.global.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.fleet.service.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name}}-service
  namespace: {{ .Release.Namespace}}
spec:
  ports:
  - name: fleet
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fleet
    release: {{ .Release.Name }}
    {{- with .Values.fleet.deployment.podLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP