apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ###############################
  nodeSelector:
    kubernetes.io/arch: arm64
  ###############################
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80